export interface IFarmTypes {
  SET_FARMS: string;
  SET_UTILS: string;
  UPDATE_ASSESSMENT: string;
  CREATE_ASSESSMENT: string;
  UPDATE_HARVEST: string;
  CREATE_HARVEST: string;
  UPDATE_SEEDING: string;
  CREATE_SEEDING: string;
};

export const FARM_TYPES: IFarmTypes = {
  SET_FARMS: 'SET_FARMS',
  SET_UTILS: 'SET_UTILS',
  UPDATE_ASSESSMENT: 'UPDATE_ASSESSMENT',
  CREATE_ASSESSMENT: 'CREATE_ASSESSMENT',
  UPDATE_HARVEST: 'UPDATE_HARVEST',
  CREATE_HARVEST: 'CREATE_HARVEST',
  UPDATE_SEEDING: 'UPDATE_SEEDING',
  CREATE_SEEDING: 'CREATE_SEEDING',
};
