export interface IUITypes {
  SET_CONNECTION: string;
  SET_ERROR: string;
  REMOVE_ERROR: string;
  SET_NETSUITE_DATA_LOADING: string;
}

export const UI_TYPES: IUITypes = {
  SET_CONNECTION: 'SET_CONNECTION',
  SET_ERROR: 'SET_ERROR',
  REMOVE_ERROR: 'REMOVE_ERROR',
  SET_NETSUITE_DATA_LOADING: 'SET_NETSUITE_DATA_LOADING',
};
